name: Lighthouse CI
on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://dllxxun.github.io/movielist.github.io/
          uploadArtifacts: true
          temporaryPublicStorage: true