name: Deployment Notifications

on:
  workflow_run:
    workflows: ["Branch Deploy"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: OSCloudysky/UniNotify@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          messageType: 'slack'
          slackToken: ${{ secrets.SLACK_API_TOKEN }}